@startuml

skinparam monochrome true

header
@autor: sebastian lesse
endheader

mainframe activity: architecture - System-context (user-view)

actor USER

component rpi_control [
	<system>
	RPi-Control
]

node SENSOR {
}

node OPEN_HAB2 {
}

node RELAIS {
}

node CONSUMER_ELECTRONIC {

}

[rpi_control] -up- "m" USER : webbroswer
[rpi_control] -- "n" SENSOR
[rpi_control] -- "n" RELAIS
[rpi_control] -left- "1" OPEN_HAB2
[rpi_control] -right- "n" CONSUMER_ELECTRONIC

note right of RELAIS
switch on/off
external devices
like lights
end note

note right of SENSOR
get environment data
from several sensor-units
like ambient-light, temperature
humidity
end note

note right of CONSUMER_ELECTRONIC
remote control of
tv, radio, media-player
end note

note left of OPEN_HAB2
central management system
for system-control and display
of system-data
end note

@enduml