/**
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * @file   command_line_handler_remote_control.h
 * @author Sebastian Lesse
 * @date   2021 / 05 / 23
 * @brief  Holds definitions to handle ir-remote command-line arguments
 * and to generate ir-commands
 * 
 */

// --------------------------------------------------------------------------------

#ifndef CLI_REMOTE_CONTROL_CMD_NAME_MAX_LENGTH
#define CLI_REMOTE_CONTROL_CMD_NAME_MAX_LENGTH              32
#endif

#ifndef CLI_REMOTE_CONTROL_CMD_HEX_STR_LENGTH
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LENGTH               16
#endif

// --------------------------------------------------------------------------------

/**
 * @brief Structure to hold a command name and
 * it's data in a hex-sstring format
 * 
 */
typedef struct {
    char cmd_name[CLI_REMOTE_CONTROL_CMD_NAME_MAX_LENGTH];
    char cmd_hex_str[CLI_REMOTE_CONTROL_CMD_HEX_STR_LENGTH];
} CLI_REMOTE_CONTROL_COMMAND_PAIR;

// --------------------------------------------------------------------------------

#define CLI_REMOTE_SIZEOF_COMMAND_PAIR_TABLE(cmd_pair_table)    (sizeof(cmd_pair_table) / sizeof(CLI_REMOTE_CONTROL_COMMAND_PAIR))

// --------------------------------------------------------------------------------

/**
 * @brief Names of available JVS commands
 * 
 */

#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_POWER_ON      "jvc_radio_power_on\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_VOLUME_DOWN   "jvc_radio_volume_down\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_VOLUME_UP     "jvc_radio_volume_up\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_VOLUME_MUTE   "jvc_radio_volume_mute\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_PLAY          "jvc_radio_play\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_PAUSE         "jvc_radio_pause\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_STOP          "jvc_radio_stop\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_BASS_UP       "jvc_radio_bass_up\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_BASS_DOWN     "jvc_radio_bass_down\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_SOUND_MODE    "jvc_radio_sound_mode\0"

/**
 * @brief Commands as HEX-string of available JVC-Commands
 * 
 */

#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_POWER_ON       "070C11040B020201"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_VOLUME_DOWN    "070C11040B020204"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_VOLUME_UP      "070C11040B020203"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_VOLUME_MUTE    "070C11040B02021E"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_PLAY           "070C11040B020218"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_PAUSE          "070C11040B020219"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_STOP           "070C11040B02021A"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_BASS_UP        "070C11040B02021B"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_BASS_DOWN      "070C11040B02021C"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_SOUND_MODE     "070C11040B02021D"

/**
 * @brief Combination of available JVC command names and HEX-string
 * to use it for a array declaration
 * 
 */

#define CLI_REMOTE_CONTROL_CMD_ARRAY_JVC                                                                        \
    { CLI_REMOTE_CONTROL_NAME_JVC_RADIO_POWER_ON,       CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_POWER_ON }, \
    { CLI_REMOTE_CONTROL_NAME_JVC_RADIO_VOLUME_DOWN,    CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_VOLUME_DOWN }, \
    { CLI_REMOTE_CONTROL_NAME_JVC_RADIO_VOLUME_UP,      CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_VOLUME_UP }, \
    { CLI_REMOTE_CONTROL_NAME_JVC_RADIO_VOLUME_MUTE,    CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_VOLUME_MUTE }, \
    { CLI_REMOTE_CONTROL_NAME_JVC_RADIO_PLAY,           CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_PLAY }, \
    { CLI_REMOTE_CONTROL_NAME_JVC_RADIO_PAUSE,          CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_PAUSE }, \
    { CLI_REMOTE_CONTROL_NAME_JVC_RADIO_STOP,           CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_STOP }, \
    { CLI_REMOTE_CONTROL_NAME_JVC_RADIO_BASS_UP,        CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_BASS_UP }, \
    { CLI_REMOTE_CONTROL_NAME_JVC_RADIO_BASS_DOWN,      CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_BASS_DOWN }, \
    { CLI_REMOTE_CONTROL_NAME_JVC_RADIO_SOUND_MODE,     CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_SOUND_MODE }

// --------------------------------------------------------------------------------

/**
 * @brief Names of available Samsung commands
 * 
 */

#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_POWER_ON        "samsung_tv_power_on\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_VOLUME_DOWN        "samsung_tv_volume_down\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_VOLUME_UP        "samsung_tv_volume_up\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_VOLUME_MUTE        "samsung_tv_volume_mute\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_PLAY            "samsung_tv_play\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_PAUSE        "samsung_tv_pause\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_STOP            "samsung_tv_stop\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_UP        "samsung_tv_channel_up\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_DOWN        "samsung_tv_channel_down\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_LIST        "samsung_tv_channel_list\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_1        "samsung_tv_channel_1\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_2        "samsung_tv_channel_2\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_3        "samsung_tv_channel_3\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_4        "samsung_tv_channel_4\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_5        "samsung_tv_channel_5\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_6        "samsung_tv_channel_6\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_7        "samsung_tv_channel_7\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_8        "samsung_tv_channel_8\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_9        "samsung_tv_channel_9\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_0        "samsung_tv_channel_0\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_UP        "samsung_tv_arrow_up\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_DOWN        "samsung_tv_arrow_down\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_RIGHT        "samsung_tv_arrow_right\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_LEFT        "samsung_tv_arrow_left\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ENTER        "samsung_tv_enter\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_RETURN        "samsung_tv_return\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_EXIT            "samsung_tv_exit\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_GUIDE        "samsung_tv_program_guide\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_HOME            "samsung_tv_home\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_SOURCE        "samsung_tv_source\0"

/**
 * @brief Commands as HEX-string of available Samsung-Commands
 * 
 */

#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_POWER_ON    "070C11040B010101"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_VOLUME_DOWN    "070C11040B010104"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_VOLUME_UP    "070C11040B010103"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_VOLUME_MUTE    "070C11040B01011E"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_PLAY        "070C11040B010118"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_PAUSE        "070C11040B010119"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_STOP        "070C11040B01011A"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_UP    "070C11040B010105"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_DOWN    "070C11040B010106"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_LIST    "070C11040B010121"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_1    "070C11040B010108"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_2    "070C11040B010109"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_3    "070C11040B01010A"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_4    "070C11040B01010B"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_5    "070C11040B01010C"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_6    "070C11040B01010D"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_7    "070C11040B01010E"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_8    "070C11040B01010F"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_9    "070C11040B010110"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_0    "070C11040B010107"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_UP    "070C11040B010114"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_DOWN    "070C11040B010115"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_RIGHT    "070C11040B010117"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_LEFT    "070C11040B010116"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ENTER        "070C11040B010112"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_RETURN    "070C11040B010113"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_EXIT        "070C11040B010112"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_GUIDE        "070C11040B01011F"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_HOME        "070C11040B010120"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_SOURCE    "070C11040B010122"

/**
 * @brief Combination of available Samsung command names and HEX-string
 * to use it for a array declaration
 * 
 */

#define CLI_REMOTE_CONTROL_CMD_ARRAY_SAMSUNG                                                                            \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_POWER_ON,      CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_POWER_ON }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_VOLUME_DOWN,   CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_VOLUME_DOWN }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_VOLUME_UP,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_VOLUME_UP }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_VOLUME_MUTE,   CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_VOLUME_MUTE }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_PLAY,          CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_PLAY }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_PAUSE,         CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_PAUSE }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_STOP,          CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_STOP }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_UP,    CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_UP }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_DOWN,  CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_DOWN }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_LIST,  CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_LIST }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_1,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_1 }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_2,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_2 }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_3,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_3 }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_4,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_4 }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_5,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_5 }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_6,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_6 }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_7,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_7 }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_8,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_8 }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_9,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_9 }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_0,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_0 }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_UP,         CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_UP }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_DOWN,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_DOWN }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_RIGHT,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_RIGHT }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_LEFT,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_LEFT }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ENTER,         CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ENTER }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_RETURN,         CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_RETURN }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_EXIT,         CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_EXIT }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_GUIDE,         CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_GUIDE }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_HOME,         CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_HOME }, \
    { CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_SOURCE,         CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_SOURCE }

// --------------------------------------------------------------------------------

/**
 * @brief Names of available LED-Light commands
 * 
 */

#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_ON            "led_light_on\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_OFF           "led_light_off\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_BRIGHTER      "led_light_brighter\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_DARKER        "led_light_darker\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_FLASH         "led_light_flash\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_STROBE        "led_light_strobe\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_FADE          "led_light_fade\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_SMOOTH        "led_light_smooth\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_WHITE         "led_light_white\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_RED           "led_light_red\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_RED_INDIAN    "led_light_red_indian\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_COPPER        "led_light_copper\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_ORANGE        "led_light_orange\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_YELLOW        "led_light_yellow\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_GREEN_FOREST  "led_light_green_forest\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_GREEN         "led_light_green\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_BLUE_AZURE    "led_light_blue_azure\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_BLUE_STEEL    "led_light_blue_steel\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_JADE          "led_light_jade\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_BLUE          "led_light_blue\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_BLUE_MARINE   "led_light_blue_marine\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_EGGPLANT      "led_light_eggplant\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_PURPLE        "led_light_purple\0"
#define CLI_REMOTE_CONTROL_NAME_LED_LIGHT_PINK          "led_light_pink\0"

/**
 * @brief Commands as HEX-string of available LED-Light commands
 * 
 */

#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_ON             "070C11040B04F101"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_OFF            "070C11040B04F102"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_BRIGHTER       "070C11040B04F12A"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_DARKER         "070C11040B04F12B"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_FLASH          "070C11040B04F12C"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_STROBE         "070C11040B04F12D"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_FADE           "070C11040B04F12E"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_SMOOTH         "070C11040B04F12F"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_WHITE          "070C11040B04F130"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_RED            "070C11040B04F131"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_RED_INDIAN     "070C11040B04F132"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_COPPER         "070C11040B04F133"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_ORANGE         "070C11040B04F134"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_YELLOW         "070C11040B04F135"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_GREEN_FOREST   "070C11040B04F136"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_GREEN          "070C11040B04F137"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_BLUE_AZURE     "070C11040B04F138"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_BLUE_STEEL     "070C11040B04F139"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_JADE           "070C11040B04F13A"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_BLUE           "070C11040B04F13B"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_BLUE_MARINE    "070C11040B04F13C"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_EGGPLANT       "070C11040B04F13D"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_PURPLE         "070C11040B04F13E"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_PINK           "070C11040B04F13F"

/**
 * @brief Combination of available Led-Lights command names and HEX-string
 * to use it for a array declaration
 * 
 */

#define CLI_REMOTE_CONTROL_CMD_ARRAY_LED_LIGHTS                                                                                 \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_ON,                 CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_ON },                  \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_OFF,                CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_OFF },                 \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_BRIGHTER,           CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_BRIGHTER },            \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_DARKER,             CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_DARKER },              \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_FLASH,              CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_FLASH },               \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_STROBE,             CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_STROBE },              \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_FADE,               CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_FADE },                \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_SMOOTH,             CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_SMOOTH },              \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_WHITE,              CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_WHITE },               \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_RED,                CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_RED },                 \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_RED_INDIAN,         CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_RED_INDIAN },          \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_COPPER,             CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_COPPER },              \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_ORANGE,             CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_ORANGE },              \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_YELLOW,             CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_YELLOW },              \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_GREEN_FOREST,       CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_GREEN_FOREST },        \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_GREEN,              CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_GREEN },               \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_BLUE_AZURE,         CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_BLUE_AZURE },          \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_BLUE_STEEL,         CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_BLUE_STEEL },          \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_JADE,               CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_JADE },                \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_BLUE,               CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_BLUE },                \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_BLUE_MARINE,        CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_BLUE_MARINE },         \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_EGGPLANT,           CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_EGGPLANT },            \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_PURPLE,             CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_PURPLE },              \
        { CLI_REMOTE_CONTROL_NAME_LED_LIGHT_PINK,               CLI_REMOTE_CONTROL_CMD_HEX_STR_LED_LIGHT_PINK }

// --------------------------------------------------------------------------------

/**
 * @brief Names of available SONY_BDPLAYER commands
 * 
 */

#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_ON            "SONY_BDPLAYER_on\0"
#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_OFF           "SONY_BDPLAYER_off\0"
#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_PLAY          "SONY_BDPLAYER_play\0"
#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_STOP          "SONY_BDPLAYER_stop\0"
#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_PAUSE         "SONY_BDPLAYER_pause\0"
#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_AUDIO_LANG    "SONY_BDPLAYER_audio_language\0"
#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_SUBTITLE_LANG "SONY_BDPLAYER_subtitle_language\0"
#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_EJECT         "SONY_BDPLAYER_eject\0"
#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_RETURN        "SONY_BDPLAYER_return\0"
#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_TOP_MENU      "SONY_BDPLAYER_top_menu\0"
#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_POP_UP_MENU   "SONY_BDPLAYER_pop_up_menu\0"
#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_NEXT          "SONY_BDPLAYER_next\0"
#define CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_PREVIOUS      "SONY_BDPLAYER_previous\0"

/**
 * @brief Commands as HEX-string of available SONY_BDPLAYER-Commands
 * 
 */

#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_ON             "070C11040B030301"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_OFF            "070C11040B030302"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_PLAY           "070C11040B030318"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_STOP           "070C11040B03031A"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_PAUSE          "070C11040B030319"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_AUDIO_LANG     "070C11040B030323"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_SUBTITLE_LANG  "070C11040B030324"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_EJECT          "070C11040B030325"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_RETURN         "070C11040B030313"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_TOP_MENU       "070C11040B030326"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_POP_MENU       "070C11040B030327"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_NEXT           "070C11040B030328"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_PREVIOUS       "070C11040B030329"

/**
 * @brief Combination of available Led-Lights command names and HEX-string
 * to use it for a array declaration
 * 
 */

#define CLI_REMOTE_CONTROL_CMD_ARRAY_SONY_BDPLAYER                                                                              \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_ON,             CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_ON },              \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_OFF,            CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_OFF },             \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_PLAY,           CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_PLAY },            \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_STOP,           CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_STOP },            \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_PAUSE,          CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_PAUSE },           \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_AUDIO_LANG,     CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_AUDIO_LANG },      \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_SUBTITLE_LANG,  CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_SUBTITLE_LANG },   \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_EJECT,          CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_EJECT },           \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_RETURN,         CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_RETURN },          \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_TOP_MENU,       CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_TOP_MENU },        \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_POP_UP_MENU,    CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_POP_MENU },        \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_NEXT,           CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_NEXT },            \
        { CLI_REMOTE_CONTROL_NAME_SONY_BDPLAYER_PREVIOUS,       CLI_REMOTE_CONTROL_CMD_HEX_STR_SONY_BDPLAYER_PREVIOUS }

// --------------------------------------------------------------------------------

#define CLI_REMOTE_CONTROL_CMD_ARRAY_ALL                                \
    CLI_REMOTE_CONTROL_CMD_ARRAY_JVC,                                   \
    CLI_REMOTE_CONTROL_CMD_ARRAY_SAMSUNG,                               \
    CLI_REMOTE_CONTROL_CMD_ARRAY_LED_LIGHTS,                            \
    CLI_REMOTE_CONTROL_CMD_ARRAY_SONY_BDPLAYER


// --------------------------------------------------------------------------------

/**
 * @brief 
 * 
 * @param parameter 
 */
void command_line_handler_remote_control(const char* parameter);
