/*! 
 * --------------------------------------------------------------------------------
 *
 * \file	command_line_handler_remote_control.h
 * \author	sebastian lesse
 *
 * --------------------------------------------------------------------------------
 */

// --------------------------------------------------------------------------------

#include "config.h"

// --------------------------------------------------------------------------------

#ifndef CLI_REMOTE_CONTROL_CMD_NAME_MAX_LENGTH
#define CLI_REMOTE_CONTROL_CMD_NAME_MAX_LENGTH				32
#endif

#ifndef CLI_REMOTE_CONTROL_CMD_HEX_STR_LENGTH
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_LENGTH				16
#endif

// --------------------------------------------------------------------------------

typedef struct {
	char cmd_name[CLI_REMOTE_CONTROL_CMD_NAME_MAX_LENGTH];
	char cmd_hex_str[CLI_REMOTE_CONTROL_CMD_HEX_STR_LENGTH];
} CLI_REMOTE_CONTROL_COMMAND_PAIR;

// --------------------------------------------------------------------------------

#define CLI_REMOTE_SIZEOF_COMMAND_PAIR_TABLE(cmd_pair_table)		(sizeof(cmd_pair_table) / sizeof(CLI_REMOTE_CONTROL_COMMAND_PAIR))

// --------------------------------------------------------------------------------

#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_POWER_ON		"jvc_radio_power_on\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_VOLUME_DOWN		"jvc_radio_volume_down\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_VOLUME_UP		"jvc_radio_volume_up\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_VOLUME_MUTE		"jvc_radio_volume_mute\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_PLAY			"jvc_radio_play\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_PAUSE			"jvc_radio_pause\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_STOP			"jvc_radio_stop\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_BASS_UP		"jvc_radio_bass_up\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_BASS_DOWN		"jvc_radio_bass_down\0"
#define CLI_REMOTE_CONTROL_NAME_JVC_RADIO_SOUND_MODE		"jvc_radio_sound_mode\0"

#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_POWER_ON	"070C11040B020201"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_VOLUME_DOWN	"070C11040B020204"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_VOLUME_UP	"070C11040B020203"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_VOLUME_MUTE	"070C11040B02021E"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_PLAY		"070C11040B020218"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_PAUSE		"070C11040B020219"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_STOP		"070C11040B02021A"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_BASS_UP	"070C11040B02021B"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_BASS_DOWN	"070C11040B02021C"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_SOUND_MODE	"070C11040B02021D"

#define CLI_REMOTE_CONTROL_CMD_ARRAY_JVC			{ CLI_REMOTE_CONTROL_NAME_JVC_RADIO_POWER_ON, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_POWER_ON }, \
								{ CLI_REMOTE_CONTROL_NAME_JVC_RADIO_VOLUME_DOWN, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_VOLUME_DOWN }, \
								{ CLI_REMOTE_CONTROL_NAME_JVC_RADIO_VOLUME_UP, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_VOLUME_UP }, \
								{ CLI_REMOTE_CONTROL_NAME_JVC_RADIO_VOLUME_MUTE, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_VOLUME_MUTE }, \
								{ CLI_REMOTE_CONTROL_NAME_JVC_RADIO_PLAY, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_PLAY }, \
								{ CLI_REMOTE_CONTROL_NAME_JVC_RADIO_PAUSE, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_PAUSE }, \
								{ CLI_REMOTE_CONTROL_NAME_JVC_RADIO_STOP, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_STOP }, \
								{ CLI_REMOTE_CONTROL_NAME_JVC_RADIO_BASS_UP, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_BASS_UP }, \
								{ CLI_REMOTE_CONTROL_NAME_JVC_RADIO_BASS_DOWN, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_BASS_DOWN }, \
								{ CLI_REMOTE_CONTROL_NAME_JVC_RADIO_SOUND_MODE, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_JVC_RADIO_SOUND_MODE }

// --------------------------------------------------------------------------------

#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_POWER_ON		"samsung_tv_power_on\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_VOLUME_DOWN		"samsung_tv_volume_down\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_VOLUME_UP		"samsung_tv_volume_up\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_VOLUME_MUTE		"samsung_tv_volume_mute\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_PLAY			"samsung_tv_play\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_PAUSE		"samsung_tv_pause\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_STOP			"samsung_tv_stop\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_UP		"samsung_tv_channel_up\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_DOWN		"samsung_tv_channel_down\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_LIST		"samsung_tv_channel_list\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_1		"samsung_tv_channel_1\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_2		"samsung_tv_channel_2\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_3		"samsung_tv_channel_3\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_4		"samsung_tv_channel_4\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_5		"samsung_tv_channel_5\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_6		"samsung_tv_channel_6\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_7		"samsung_tv_channel_7\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_8		"samsung_tv_channel_8\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_9		"samsung_tv_channel_9\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_0		"samsung_tv_channel_0\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_UP		"samsung_tv_arrow_up\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_DOWN		"samsung_tv_arrow_down\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_RIGHT		"samsung_tv_arrow_right\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_LEFT		"samsung_tv_arrow_left\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ENTER		"samsung_tv_enter\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_RETURN		"samsung_tv_return\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_EXIT			"samsung_tv_exit\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_GUIDE		"samsung_tv_program_guide\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_HOME			"samsung_tv_home\0"
#define CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_SOURCE		"samsung_tv_source\0"

#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_POWER_ON	"070C11040B010101"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_VOLUME_DOWN	"070C11040B010104"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_VOLUME_UP	"070C11040B010103"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_VOLUME_MUTE	"070C11040B01011E"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_PLAY		"070C11040B010118"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_PAUSE		"070C11040B010119"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_STOP		"070C11040B01011A"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_UP	"070C11040B010105"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_DOWN	"070C11040B010106"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_LIST	"070C11040B010121"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_1	"070C11040B010108"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_2	"070C11040B010109"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_3	"070C11040B01010A"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_4	"070C11040B01010B"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_5	"070C11040B01010C"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_6	"070C11040B01010D"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_7	"070C11040B01010E"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_8	"070C11040B01010F"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_9	"070C11040B010110"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_0	"070C11040B010107"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_UP	"070C11040B010114"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_DOWN	"070C11040B010115"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_RIGHT	"070C11040B010117"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_LEFT	"070C11040B010116"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ENTER		"070C11040B010112"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_RETURN	"070C11040B010113"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_EXIT		"070C11040B010112"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_GUIDE		"070C11040B01011F"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_HOME		"070C11040B010120"
#define CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_SOURCE	"070C11040B010122"

#define CLI_REMOTE_CONTROL_CMD_ARRAY_SAMSUNG			{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_POWER_ON, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_POWER_ON }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_VOLUME_DOWN, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_VOLUME_DOWN }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_VOLUME_UP, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_VOLUME_UP }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_VOLUME_MUTE, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_VOLUME_MUTE }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_PLAY, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_PLAY }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_PAUSE, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_PAUSE }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_STOP, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_STOP }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_UP, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_UP }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_DOWN, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_DOWN }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_LIST, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_LIST }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_1, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_1 }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_2, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_2 }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_3, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_3 }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_4, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_4 }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_5, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_5 }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_6, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_6 }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_7, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_7 }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_8, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_8 }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_9, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_9 }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_CHANNEL_0, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_CHANNEL_0 }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_UP, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_UP }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_DOWN, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_DOWN }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_RIGHT, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_RIGHT }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ARROW_LEFT, 	CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ARROW_LEFT }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_ENTER, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_ENTER }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_RETURN, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_RETURN }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_EXIT, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_EXIT }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_GUIDE, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_GUIDE }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_HOME, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_HOME }, \
								{ CLI_REMOTE_CONTROL_NAME_SAMSUNG_TV_SOURCE, 		CLI_REMOTE_CONTROL_CMD_HEX_STR_SAMSUNG_TV_SOURCE }

// --------------------------------------------------------------------------------

void command_line_handler_remote_control(const char* parameter);


