@startuml rpi_control_frmwrk_diagram_component_lcd_task

skinparam monochrome true
'skinparam linetype ortho
skinparam style strictuml

frame "component: rpi_control_frmwrk - structure - LCD-Task" {

    package "UI" {
        component LCD_Task #DDDDDD {

            component fifo [
                <<FIFO>>
                Text Line Fifo
            ]

            component slot_line [
                <<SLOT>>
                NEW-LINE
            ]

            component control_task [
                <<Task>>
                Control-Task
            ]

            component lcd_driver [
                <<Driver>>
                LCD-Driver
            ]

            slot_line -right-> fifo : store new line

            control_task -up-> fifo : read next line
            control_task -left-> lcd_driver : update display
        }
    }

    package "MCU-Task-Controller" {
        component task_controller[
            <<Controller>>
            MCU-Task-Controller
        ]
    }

    package "Kernel" {
        component signal_slot [
            <<Signal-Slot>>
            Signal-SLot
        ]

        url of signal_slot is [[www.google.de{This is Dog}]]
    }

    package "Driver" {
        component gpio_driver [
            <<Driver>>
            GPIO-Driver
        ]
    }

    signal_slot -down-> slot_line : SIGNAL(NEW-LINE)
    task_controller -up-> control_task : schedules
    lcd_driver -down-> gpio_driver

}

@enduml
