@startuml rpi_control_frmwrk_diagram_pacakge_main_structure

skinparam monochrome true
'skinparam linetype ortho
'skinparam style strictuml

frame "component: Rpi-Control-Frmwrk - Structure - Main Overview" {

    folder "Projects" {
        component application [
            <<component>>
            Application
        ]
    }

    folder "SOC" {
        component soc [
            <<driver>>
            SOC-Driver
        ]
    }

    folder "Framework" {

        component kernel [
            <<component>>
            Kernel
        ]

        component app_task [
            <<component>>
            App-Task
        ]

        component driver [
            <<component>>
            Driver
        ]

        component cmd_handling [
            <<component>>
            Command-Hanndling
        ]

        component protocol [
            <<component>>
            Protocol
        ]

        component modules [
            <<component>>
            Modules
        ]

        kernel -down- app_task
        kernel -left- cmd_handling
        kernel -right- protocol
        kernel -- driver
        kernel -- modules

        url of kernel is [[../readme/readme_kernel.h {Click: Go to}]]

    }

    application -down-> "Framework"
    "Framework" -up-> soc

}
@enduml
