#ifndef _LOCAL_ASIC_INFORMATION_SHT31_H_
#define _LOCAL_ASIC_INFORMATION_SHT31_H_

#define SHT31_OPERATION_TIMEOUT_MS				250

#define SHT31_STARTUP_TIME_MS					10

#define SHT31_COMMAND_CLEAR_STATUS_REGISTER			0x3041

#define SHT31_COMMAND_WITH_CLK_STRECHTING_HIGH_REPEATABILITY	0x2C06
#define SHT31_COMMAND_WITH_CLK_STRECHTING_MEDIUM_REPEATABILITY	0x2C0D
#define SHT31_COMMAND_WITH_CLK_STRECHTING_LOW_REPEATABILITY	0x2C10

#define SHT31_COMMAND_NO_CLK_STRECHTING_HIGH_REPEATABILITY	0x2400
#define SHT31_COMMAND_NO_CLK_STRECHTING_MEDIUM_REPEATABILITY	0x2408
#define SHT31_COMMAND_NO_CLK_STRECHTING_LOW_REPEATABILITY	0x2416

#define SHT31_SET_COMMAND(command, p_buffer)			p_buffer[0] = (u8)(command >> 8); \
								p_buffer[1] = (u8)(command &0x00FF);

#define SHT31_MEASUREMENT_COMMAND_LENGTH			2
#define SHT31_MEASRUEMENT_ANSWER_LENGTH				6

#define SHT31_COMMAND_STATUS_REGISTER				{0xF3, 0x20}

#define SHT31_TEMPERATURE_FIXPOINT_FACTOR_M			0x00AF
#define SHT31_TEMPERATURE_FIXPOINT_FACTOR_B			0x002D

#define SHT31_HUMIDITY_FIXPOINT_FACTOR_M			0x0064

#define SHT31_BUS_ADDRESS_1					0x44
#define SHT31_BUS_ADDRESS_2					0x45

#define SHT31_INDEX_OF_TEMPERATURE_MSB_IN_ANSWER		0
#define SHT31_INDEX_OF_TEMPERATURE_LSB_IN_ANSWER		1
#define SHT31_INDEX_OF_HUMIDITY_MSB_IN_ANSWER			3
#define SHT31_INDEX_OF_HUMIDITY_LSB_IN_ANSWER			4

#define SHT31_MAXIMUM_MEASSUREABLE_TEMPERATURE			127
#define SHT31_MAXIMUM_MEASSUREABLE_HUMIDITY			100

#define SHT31_MEASUREMENT_TIME_LOW_REPEATABILITY_MS		(15 + 1) /* including tolerance */

#define SHT31_ADC_TO_TEMPERATURE(p_u8_buffer)

#endif // _LOCAL_ASIC_INFORMATION_SHT31_H_




