#ifndef _PROTOCOL_DRIVER_INTERFACE_H_
#define _PROTOCOL_DRIVER_INTERFACE_H_

/*
 */
typedef void (*PROTOCOL_DRIVER_INTERFACE_RX_COMPLETE_CALLBACK)	(void);

/*
 */
typedef void (*PROTOCOL_DRIVER_INTERFACE_TX_COMPLETE_CALLBACK)	(void);


typedef struct PROTOCOL_DRIVER_INTERFACE {
	
	PROTOCOL_DRIVER_INTERFACE_RX_COMPLETE_CALLBACK rx_complete;
	PROTOCOL_DRIVER_INTERFACE_TX_COMPLETE_CALLBACK tx_complete;
	
} PROTOCOL_DRIVER_INTERFACE;

#endif // _PROTOCOL_DRIVER_INTERFACE_H_
