@startuml

skinparam monochrome true

partition "activity: Message-Executer process COM-command" {
start

:prepare command;

if (command is valid) then (no)
	#pink:INVALID_COMMAND>

else (yes)

	#pink:NEW_COM_COMMAND_RECEIVED>
	:wait for response;

	if () then (TIMEOUT)
		#pink:RESPONSE_TIMEOUT>
	else ()
		:prepare response;
		#pink:RESPONSE_RECEIVED<
	endif
endif

end

}

footer Author: Sebastian Lesse

@enduml