#-----------------------------------------------------------------------------
#       Makefile fuer WebConfig - Fullversion
#-----------------------------------------------------------------------------

PROJECT = ProxEntry_Legic

CONFIG_MEM_SCHEME = 0x21BA0002
BASE_PATH    = ../../../..
include $(BASE_PATH)/local.mk
include $(DE_FRM)/make/webconfig_full.mk

IARSRCS_WEBCONFIG_ROAD_SCRIPT = webconfig_road.cfg

include $(GENERIC_TARGET_RULES) $(MAKE_TARGET_RULES)
