@startuml

skinparam monochrome true

header
@autor: sebastian lesse
endheader

mainframe component: rpi-protocol-client - interface

component rpi_protocol_client [
	<module>
	RPi Protocol-Client
]

package "SIGNALS" {
	[rpi_protocol_client] -down-> LEAVE_SLEEP
	[rpi_protocol_client] -down-> ENTER_SLEEP
	[rpi_protocol_client] -down-> INVALID_COMMAND_RECEIVED
	[rpi_protocol_client] -down-> COMMAND_RECEIVED
}

@enduml