@startuml movement_detection_context

'***************************************************************************

skinparam monochrome true
' skinparam linetype ortho

'***************************************************************************

frame "class: RPi-Control - Movement-Detection - Context" {

'***************************************************************************

    folder "kernel" {

        interface Task {

        }

        interface singal_slot {

        }
    }

    folder "driver" {
        class sensor_driver {

        }
    }

    folder "modules" {
        interface sensor_interface {

        }

        class movement_detection  {

        }
    }

    movement_detection .up.|> Task
    movement_detection .up.> singal_slot : <uses>
    movement_detection .right.> sensor_interface : <uses>

    sensor_driver -down-|> sensor_interface

'***************************************************************************

}

'***************************************************************************

@enduml
