@startuml

skinparam monochrome true

header
@autor: sebastian lesse
endheader

mainframe activity: architecture - module configuration

start
(A)
:Wait for User CFG;

split
	#pink:CFG-Object<
split again
	#pink:CFG Complete<
	stop
end split

:parse CFG-Object;

if (object belongs to this module) then (yes)
	:store CFG-Object value into ram-variable;
else (no)
	(A)
	detach
endif
	
(A)

@enduml