@startuml

skinparam monochrome true

header
@autor: sebastian lesse
endheader

mainframe activity: MQTT-Interface - message arrived

start

if (qeue is full) then (no)
	:load message from mqtt;
	:enqeue new message;
	:SET_STATUS(message_arrived);
else (yes)

endif
stop

@enduml