@startuml

skinparam monochrome true

header
@autor: sebastian lesse
endheader

mainframe component: mqtt-interface - interface

component mqtt_interface [
	<module>
	MQTT-Interface
]

package "SIGNALS" {
	[mqtt_interface] -down-> CONNECT_ESTABLISHED
	[mqtt_interface] -down-> CONNECTION_LOST
	[mqtt_interface] -down-> MESSAGE_RECEIVED
	[mqtt_interface] -down-> MESSAGE_SEND_FAILED
	[mqtt_interface] -down-> MESSAGE_SEND_SUCCEEDED
	[mqtt_interface] -down-> MESSAGE_TO_SEND
	note left
	triggered by extern
	end note
}

package "SLOTS" {
	[mqtt_interface] <-up- NEW_CFG_OBJECT
	[mqtt_interface] <-up- CFG_COMPLETE
	[mqtt_interface] <-up- CFG_ESSAGE_TO_SEND
}

@enduml