@startuml

skinparam monochrome true

header
@autor: sebastian lesse
endheader

mainframe activity: MQTT-Interface - response received

start

#pink:RESPONSE_RECEIVED<

if (qeue is full) then (no)
	:enqeue response;
	:SET_STATUS(response_received);
else (yes)

endif
stop

@enduml