@startuml

skinparam monochrome true

header
@autor: sebastian lesse
endheader

mainframe activity: MQTT-Interface - main process

start

partition "activity: MQTT-Interface - initialize" {
	:initialize;
}

#lightblue:(S)

partition "activity: MQTT-Interface - configure" {
	:configure;
}

#lightgreen:(C)

partition "activity: MQTT-Interface - connect ot host" {
	:connect;
}

(I)
:IDLE;

partition "activity: MQTT-Interface - check status" {
	:check MQTT-status;

	if (STATUS_IS_SET(cfg_updated)) then (yes)

		:close connection;
		#lightblue:(S)
		detach

	elseif (STATUS_IS_SET(connection_lost)) then (yes)

		:close connection;
		:SET_STATUS(unconnected);
		#pink:CONNECTION_LOST>
		#lightgreen:(C)
		detach

	elseif (STATUS_IS_SET(message_received)) then (yes)

		:deqeue message;
		#pink:MESSAGE_RECEIVED>
		(I)
		detach

	elseif (STATUS_IS_SET(response_received)) then (yes) 

		:prepare MQTT-Message;
		:send MQTT-message;

		if (message send) then (yes)
			#pink:MESSAGE_SEND_SUCESSFULL>
		else (no)
			#pink:MESSAGE_SEND_FAILED>
		endif

		(i)
		detach
	else

		(I)
		detach
	endif
}

@enduml