@startuml

skinparam monochrome true

header
@autor: sebastian lesse
endheader

mainframe activity: MQTT-Interface - response received

start

(A)
:connect to host;

if (is connected) then (yes)
	:send hello-message;
	#pink:CONNECTION_ESTABLISHED>
	:SET_STATUS(is_connected);
else (no) 
(A)
endif

end

@enduml